#!/bin/sh

if test -n "$USERID"; then
  # If a USERID is supplied, we change the user id to match it.  This
  # make is easier to write file in a directory shared with the host.
  usermod -u $USERID docker
  rm -rf /home/docker/.ipython/profile_*/pid
  rm -rf /home/docker/.ipython/profile_*/security
fi
cd /home/docker
sudo -u docker ipython notebook --ip='*' "$@"
